module.exports = {
  STACK: [
    'A# .NET',
    'A# (Axiom)',
    'A-0 System',
    'A+',
    'A++',
    'ABAP',
    'ABC',
    'ABC ALGOL',
    'ABSET',
    'ABSYS',
    'ACC',
    'Accent',
    'Ace DASL (Distributed Application Specification Language)',
    'ACL2',
    'ACT-III',
    'Action!',
    'ActionScript',
    'Actor',
    'Ada',
    'Adenine',
    'Agda',
    'Agilent VEE',
    'Agora',
    'AIMMS',
    'Aldor',
    'Alef',
    'ALF',
    'ALGOL 58',
    'ALGOL 60',
    'ALGOL 68',
    'ALGOL W',
    'Alice',
    'Alma-0',
    'AmbientTalk',
    'Amiga E',
    'AMOS',
    'AMPL',
    'AngelScript',
    'Apex (Salesforce.com)',
    'APL',
    "App Inventor for Android's visual block language",
    'AppleScript',
    'APT',
    'Arc',
    'ARexx',
    'Argus',
    'AspectJ',
    'Assembly language',
    'ATS',
    'Ateji PX',
    'AutoHotkey',
    'Autocoder',
    'AutoIt',
    'AutoLISP / Visual LISP',
    'Averest',
    'AWK',
    'Axum',
    'Active Server Pages',
    'B',
    'Babbage',
    'Bash',
    'BASIC',
    'bc',
    'BCPL',
    'BeanShell',
    'Batch (Windows/Dos)',
    'Bertrand',
    'BETA',
    'BLISS',
    'Blockly',
    'BlooP',
    'Boo',
    'Boomerang',
    'Bourne shell (including bash and ksh)',
    'BPEL',
    'Business Basic',
    'C',
    'C--',
    'C++ – ISO/IEC 14882',
    'C*',
    'C# – ISO/IEC 23270',
    'C/AL',
    'Caché ObjectScript',
    'C Shell (csh)',
    'Caml',
    'Calcpad',
    'Cayenne',
    'CDuce',
    'Cecil',
    'Cesil',
    'Céu',
    'Ceylon',
    'CFEngine',
    'Cg',
    'Ch',
    'Chapel',
    'Charity',
    'Charm',
    'CHILL',
    'CHIP-8',
    'chomski',
    'ChucK',
    'Cilk',
    'Citrine',
    'CL (IBM)',
    'Claire',
    'Clarion',
    'Clean',
    'Clipper',
    'CLIPS',
    'CLIST',
    'Clojure',
    'CLU',
    'CMS-2',
    'COBOL – ISO/IEC 1989',
    'CobolScript – COBOL Scripting language',
    'Cobra',
    'CoffeeScript',
    'ColdFusion',
    'COMAL',
    'Combined Programming Language (CPL)',
    'COMIT',
    'Common Intermediate Language (CIL)',
    'Common Lisp (also known as CL)',
    'COMPASS',
    'Component Pascal',
    'Constraint Handling Rules (CHR)',
    'COMTRAN',
    'Cool',
    'Coq',
    'Coral 66',
    'CorVision',
    'COWSEL',
    'CPL',
    'Cryptol',
    'Crystal',
    'Csound',
    'CSP',
    'CUDA',
    'Cuneiform',
    'Curl',
    'Curry',
    'Cybil',
    'Cyclone',
    'Cython',
    'D',
    "DASL (Datapoint's Advanced Systems Language)",
    'Dart',
    'Darwin',
    'DataFlex',
    'Datalog',
    'DATATRIEVE',
    'dBase',
    'dc',
    'DCL',
    'Delphi',
    'DinkC',
    'DIBOL',
    'Dog',
    'Draco',
    'DRAKON',
    'Dylan',
    'DYNAMO',
    'DAX (Data Analysis Expressions)',
    'E',
    'Ease',
    'Easy PL/I',
    'EASYTRIEVE PLUS',
    'eC',
    'ECMAScript',
    'Edinburgh IMP',
    'EGL',
    'Eiffel',
    'ELAN',
    'Elixir',
    'Elm',
    'Emacs Lisp',
    'Emerald',
    'Epigram',
    'EPL (Easy Programming Language)',
    'EPL (Eltron Programming Language)',
    'Erlang',
    'es',
    'Escher',
    'ESPOL',
    'Esterel',
    'Etoys',
    'Euclid',
    'Euler',
    'Euphoria',
    'EusLisp Robot Programming Language',
    'CMS EXEC (EXEC)',
    'EXEC 2',
    'Executable UML',
    'F',
    'F#',
    'F*',
    'Factor',
    'Falcon',
    'Fantom',
    'FAUST',
    'FFP',
    'Fjölnir',
    'FL',
    'Flavors',
    'Flex',
    'FlooP',
    'FLOW-MATIC',
    'FOCAL',
    'FOCUS',
    'FOIL',
    'FORMAC',
    '@Formula',
    'Forth',
    'Fortran – ISO/IEC 1539',
    'Fortress',
    'FoxBase',
    'FoxPro',
    'FP',
    'Franz Lisp',
    'F-Script',
    'G',
    'Game Maker Language',
    'GameMonkey Script',
    'GAMS',
    'GAP',
    'G-code',
    'GDScript',
    'Genie',
    'GDL',
    'GJ',
    'GEORGE',
    'GLSL',
    'GNU E',
    'GM',
    'Go',
    'Go!',
    'GOAL',
    'Gödel',
    'Golo',
    'GOM (Good Old Mad)',
    'Google Apps Script',
    'Gosu',
    'GOTRAN',
    'GPSS',
    'GraphTalk',
    'GRASS',
    'Groovy',
    'Hack',
    'HAGGIS',
    'HAL/S',
    'Halide (programming language)',
    'Hamilton C shell',
    'Harbour',
    'Hartmann pipelines',
    'Haskell',
    'Haxe',
    'Hermes',
    'High Level Assembly',
    'HLSL',
    'Hop',
    'Hopscotch',
    'Hope',
    'Hugo',
    'Hume',
    'HyperTalk',
    'Hexa',
    'Io',
    'Icon (programming language)',
    'IBM Basic assembly language',
    'IBM BASICA',
    'IBM HAScript',
    'IBM Informix-4GL',
    'IBM RPG',
    'IDL',
    'Idris',
    'J',
    'J#',
    'J++',
    'JADE',
    'JAL',
    'Janus (concurrent constraint programming language)',
    'Janus (time-reversible computing programming language)',
    'JASS',
    'Java',
    'JavaScript',
    'JCL',
    'JEAN',
    'Join Java',
    'JOSS',
    'Joule',
    'JOVIAL',
    'Joy',
    'JScript',
    'JScript .NET',
    'JavaFX Script',
    'jq',
    'Julia',
    'Jython',
    'K',
    'Kaleidoscope',
    'Karel',
    'Karel++',
    'KEE',
    'Kixtart',
    'Klerer-May System',
    'KIF',
    'Kojo',
    'Kotlin',
    'KRC',
    'KRL',
    'KRL (KUKA Robot Language)',
    'KRYPTON',
    'ksh',
    'Kodu',
    'Kv',
    'LabVIEW',
    'Ladder',
    'Lagoona',
    'LANSA',
    'Lasso',
    'LaTeX',
    'Lava',
    'LC-3',
    'Leda',
    'Legoscript',
    'LIL',
    'LilyPond',
    'Limbo',
    'Limnor',
    'LINC',
    'Lingo',
    'LIS',
    'LISA',
    'Lisp – ISO/IEC 13816',
    'Lite-C',
    'Lithe',
    'Little b',
    'LLL',
    'Logo',
    'Logtalk',
    'LotusScript',
    'LPC',
    'LSE',
    'LSL',
    'LiveCode',
    'LiveScript',
    'Lua',
    'Lucid',
    'Lustre',
    'LYaPAS',
    'Lynx',
    'M (alternative name for the MUMPS programming language)',
    'M2001',
    'M4',
    'M#',
    'Machine code',
    'MAD (Michigan Algorithm Decoder)',
    'MAD/I',
    'Magik',
    'Magma',
    'make',
    'Maude system',
    'Maple',
    'MAPPER (now part of BIS)',
    'MARK-IV (now VISION:BUILDER)',
    'Mary',
    'MASM Microsoft Assembly x86',
    'MATH-MATIC',
    'Mathematica',
    'MATLAB',
    'Maxima (see also Macsyma)',
    'Max (Max Msp – Graphical Programming Environment)',
    'MaxScript internal language 3D Studio Max',
    'Maya (MEL)',
    'MDL',
    'Mercury',
    'Mesa',
    'Metafont',
    'MetaQuotes Language (MQL4/MQL5)',
    'MHEG-5 (Interactive TV programming language)',
    'Microcode',
    'MicroScript',
    'MIIS',
    'Milk (programming language)',
    'MIMIC',
    'Mirah',
    'Miranda',
    'MIVA Script',
    'ML',
    'Model 204',
    'Modelica',
    'Modula',
    'Modula-2',
    'Modula-3',
    'Mohol',
    'MOO',
    'Mortran',
    'Mouse',
    'MPD',
    'Mathcad',
    'MSIL – deprecated name for CIL',
    'MSL',
    'MUMPS',
    'MuPAD',
    'Mutan',
    'Mystic Programming Language (MPL)',
    'NASM',
    'Napier88',
    'Neko',
    'Nemerle',
    'nesC',
    'NESL',
    'Net.Data',
    'NetLogo',
    'NetRexx',
    'NewLISP',
    'NEWP',
    'Newspeak',
    'NewtonScript',
    'Nial',
    'Nice',
    'Nickle (NITIN)',
    'Nim',
    'NPL',
    'Not eXactly C (NXC)',
    'Not Quite C (NQC)',
    'NSIS',
    'Nu',
    'NWScript',
    'NXT-G',
    'o:XML',
    'Oak',
    'Oberon',
    'OBJ2',
    'Object Lisp',
    'ObjectLOGO',
    'Object REXX',
    'Object Pascal',
    'Objective-C',
    'Objective-J',
    'Obliq',
    'OCaml',
    'occam',
    'occam-π',
    'Octave',
    'OmniMark',
    'Onyx',
    'Opa',
    'Opal',
    'OpenCL',
    'OpenEdge ABL',
    'OPL',
    'OpenVera',
    'OPS5',
    'OptimJ',
    'Orc',
    'ORCA/Modula-2',
    'Oriel',
    'Orwell',
    'Oxygene',
    'Oz',
    'P',
    'P4',
    'P′′',
    'ParaSail (programming language)',
    'PARI/GP',
    'Pascal – ISO 7185',
    'PCASTL',
    'PCF',
    'PEARL',
    'PeopleCode',
    'Perl',
    'PDL',
    'Perl 6',
    'Pharo',
    'PHP',
    'Pico',
    'Picolisp',
    'Pict',
    'Pig (programming tool)',
    'Pike',
    'PIKT',
    'PILOT',
    'Pipelines',
    'Pizza',
    'PL-11',
    'PL/0',
    'PL/B',
    'PL/C',
    'PL/I – ISO 6160',
    'PL/M',
    'PL/P',
    'PL/SQL',
    'PL360',
    'PLANC',
    'munoz',
    'Plankalkül',
    'Planner',
    'PLEX',
    'PLEXIL',
    'Plus',
    'POP-11',
    'POP-2',
    'PostScript',
    'PortablE',
    'Powerhouse',
    'PowerBuilder – 4GL GUI application generator from Sybase',
    'PowerShell',
    'PPL',
    'Processing',
    'Processing.js',
    'Prograph',
    'PROIV',
    'Prolog',
    'PROMAL',
    'Promela',
    'PROSE modeling language',
    'PROTEL',
    'ProvideX',
    'Pro*C',
    'Pure',
    'PureBasic',
    'Pure Data',
    'Python',
    'Q (equational programming language)',
    'Q (programming language from Kx Systems)',
    'Q# (Microsoft programming language)',
    'Qalb',
    'QtScript',
    'QuakeC',
    'QPL',
    'R',
    'R++',
    'Racket',
    'RAPID',
    'Rapira',
    'Ratfiv',
    'Ratfor',
    'rc',
    'REBOL',
    'Red',
    'Redcode',
    'REFAL',
    'Reia',
    'REXX',
    'Ring',
    'Rlab',
    'ROOP',
    'RPG',
    'RPL',
    'RSL',
    'RTL/2',
    'Ruby',
    'RuneScript',
    'Rust',
    'S',
    'S2',
    'S3',
    'S-Lang',
    'S-PLUS',
    'SA-C',
    'SabreTalk',
    'SAIL',
    'SALSA',
    'SAM76',
    'SAS',
    'SASL',
    'Sather',
    'Sawzall',
    'SBL',
    'Scala',
    'Scheme',
    'Scilab',
    'Script.NET',
    'Sed',
    'Seed7',
    'Self',
    'SenseTalk',
    'SequenceL',
    'Serpent',
    'SETL',
    'SIMPOL',
    'SIGNAL',
    'SiMPLE',
    'SIMSCRIPT',
    'Simula',
    'Simulink',
    'Singularity',
    'SISAL',
    'SLIP',
    'SMALL',
    'Scratch',
    'Smalltalk',
    'SML',
    'Strongtalk',
    'Snap!',
    'SNOBOL(SPITBOL)',
    'Snowball',
    'SOL',
    'Solidity',
    'SOPHAEROS',
    'SPARK',
    'Speedcode',
    'SPIN',
    'SP/k',
    'SPS',
    'SQL',
    'SQR',
    'Squeak',
    'Squirrel',
    'SR',
    'S/SL',
    'Starlogo',
    'Strand',
    'Stata',
    'Stateflow',
    'Subtext',
    'SuperCollider',
    'SuperTalk',
    'Swift (Apple programming language)',
    'Swift (parallel scripting language)',
    'SYMPL',
    'SystemVerilog',
    'T',
    'TACL',
    'TACPOL',
    'TADS',
    'TAL',
    'Tcl',
    'Tea',
    'TECO',
    'TELCOMP',
    'TeX',
    'TEX',
    'TIE',
    'TMG, compiler-compiler',
    'Tom',
    'TOM',
    'Toi',
    'Topspeed',
    'TPU',
    'Trac',
    'TTM',
    'T-SQL',
    'Transcript',
    'TTCN',
    'Turing',
    'TUTOR',
    'TXL',
    'TypeScript',
    'Tynker',
    'Ubercode',
    'UCSD Pascal',
    'Umple',
    'Unicon',
    'Uniface',
    'UNITY',
    'Unix shell',
    'UnrealScript',
    'Vala',
    'Verilog',
    'VHDL',
    'Viper',
    'Visual Basic',
    'Visual Basic .NET',
    'Visual DataFlex',
    'Visual DialogScript',
    'Visual Fortran',
    'Visual FoxPro',
    'Visual J++',
    'Visual J#',
    'Visual LISP',
    'Visual Objects',
    'Visual Prolog',
    'VSXu',
    'WATFIV, WATFOR',
    'WebDNA',
    'WebQL',
    'Whiley',
    'Winbatch',
    'Wolfram Language',
    'Wyvern',
    'X++',
    'X10',
    'XBL',
    'XC (exploits XMOS architecture)',
    'xHarbour',
    'XL',
    'Xojo',
    'XOTcl',
    'XOD (programming language)',
    'XPL',
    'XPL0',
    'XQuery',
    'XSB',
    'XSharp',
    'XSLT',
    'Xtend',
    'Yorick',
    'YQL',
    'Yoix',
    'Z notation',
    'Zebra, ZPL, ZPL2',
    'Zeno',
    'ZetaLisp',
    'ZOPL',
    'Zsh',
    'ZPL',
    'Z++',
  ],
  SKILLS: [
    'Assign Passwords and Maintain Database Access',
    'Agile Development',
    'Agile Project Methodology',
    'Amazon Web Services (AWS)',
    'Analytics',
    'Analytical',
    'Analyze and Recommend Database Improvements',
    'Analyze Impact of Database Changes to the Business',
    'Audit Database Access and Requests',
    'APIs',
    'Application and Server Monitoring Tools',
    'Applications',
    'Application Development',
    'Attention to Detail',
    'Architecture',
    'Big Data',
    'Business Analytics',
    'Business Intelligence',
    'Business Process Modeling',
    'Cloud Applications',
    'Cloud Based Visualizations',
    'Cloud Hosting Services',
    'Cloud Maintenance Tasks',
    'Cloud Management Tools',
    'Cloud Platforms',
    'Cloud Scalability',
    'Cloud Services',
    'Cloud Systems Administration',
    'Code',
    'Coding',
    'Computer',
    'Communication',
    'Configure Database Software',
    'Configuration',
    'Configuration Management',
    'Content Strategy',
    'Content Management',
    'Continually Review Processes for Improvement ',
    'Continuous Deployment',
    'Continuous Integration',
    'Critical Thinking',
    'Customer Support',
    'Database',
    'Data Analysis',
    'Data Analytics',
    'Data Imports',
    'Data Imports',
    'Data Intelligence',
    'Data Mining',
    'Data Modeling',
    'Data Science',
    'Data Strategy',
    'Data Storage',
    'Data Visualization Tools',
    'Data Visualizations',
    'Database Administration',
    'Deploying Applications in a Cloud Environment',
    'Deployment Automation Tools',
    'Deployment of Cloud Services',
    'Design',
    'Desktop Support',
    'Design',
    'Design and Build Database Management System',
    'Design Principles',
    'Design Prototypes',
    'Design Specifications',
    'Design Tools',
    'Develop and Secure Network Structures',
    'Develop and Test Methods to Synchronize Data ',
    'Developer',
    'Development',
    'Documentation',
    'Emerging Technologies',
    'File Systems',
    'Flexibility',
    'Front End Design',
    'Google Analytics',
    // "H – M"
    'Hardware',
    'Help Desk',
    'Identify User Needs ',
    'Implement Backup and Recovery Plan ',
    'Implementation',
    'Information Architecture',
    'Information Design',
    'Information Systems',
    'Interaction Design',
    'Interaction Flows',
    'Install, Maintain, and Merge Databases ',
    'Installation',
    'Integrated Technologies',
    'Integrating Security Protocols with Cloud Design',
    'Internet',
    'IT Optimization',
    'IT Security',
    'IT Soft Skills',
    'IT Solutions',
    'IT Support',
    'Languages',
    'Logical Thinking',
    'Leadership',
    'Linux',
    'Management',
    'Messaging',
    'Methodology',
    'Metrics',
    'Microsoft Office',
    'Migrating Existing Workloads into Cloud Systems',
    'Mobile Applications',
    'Motivation',
    // "N – S"
    'Networks',
    'Network Operations',
    'Networking',
    'Open Source Technology Integration',
    'Operating Systems',
    'Operations',
    'Optimize Queries on Live Data',
    'Optimizing User Experiences',
    'Optimizing Website Performance',
    'Organization',
    'Presentation',
    'Programming',
    'Problem Solving',
    'Process Flows',
    'Product Design',
    'Product Development',
    'Prototyping Methods',
    'Product Development',
    'Product Management',
    'Product Support',
    'Product Training',
    'Project Management',
    'Repairs',
    'Reporting',
    'Research Emerging Technology',
    'Responsive Design',
    'Review Existing Solutions',
    'Search Engine Optimization (SEO)',
    'Security',
    'Self Motivated',
    'Self Starting',
    'Servers',
    'Software',
    'Software Development',
    'Software Engineering',
    'Software Quality Assurance (QA)',
    'Solid Project Management Capabilities ',
    'Solid Understanding of Company’s Data Needs ',
    'Storage',
    'Strong Technical and Interpersonal Communication ',
    'Support',
    'Systems Software',
    // "T - Z"
    'Tablets',
    'Team Building',
    'Team Oriented',
    'Teamwork',
    'Technology',
    'Tech Skills',
    'Technical Support',
    'Technical Writing',
    'Testing',
    'Time Management',
    'Tools',
    'Touch Input Navigation',
    'Training',
    'Troubleshooting',
    'Troubleshooting Break-Fix Scenarios',
    'User Research',
    'User Testing',
    'Usability',
    'User-Centered Design',
    'User Experience',
    'User Flows',
    'User Interface',
    'User Interaction Diagrams',
    'User Research',
    'User Testing',
    'UI / UX',
    'Utilizing Cloud Automation Tools',
    'Virtualization',
    'Visual Design',
    'Web Analytics',
    'Web Applications',
    'Web Development',
    'Web Design',
    'Web Technologies',
    'Wireframes',
    'Work Independently',
  ],
};
